-- AI伴侣配置表
CREATE TABLE ai_companion (
    id              BIGINT       PRIMARY KEY AUTO_INCREMENT,
    user_id         BIGINT       NOT NULL COMMENT '关联用户表',
    device_id       VARCHAR(32)  NOT NULL COMMENT '设备ID',
    type            VARCHAR(8)   NOT NULL COMMENT '伴侣类型: gf=女友, bf=男友',
    avatar          VARCHAR(256) NOT NULL COMMENT '伴侣头像URL',
    default_image   VARCHAR(256) NOT NULL COMMENT '默认图片URL',
    birthday        DATETIME     NOT NULL COMMENT '出生日期',
    zodiac          VARCHAR(16)  NOT NULL COMMENT '星座: aries/taurus/.../pisces',
    chinese_zodiac  VARCHAR(16)  NOT NULL COMMENT '属相: rat/ox/tiger/.../pig',
    bazi            JSON         NOT NULL COMMENT '八字',
    wuxing          JSON         NOT NULL COMMENT '五行',
    `character`     VARCHAR(32)  NOT NULL COMMENT '角色',
    occupation      VARCHAR(32)  NOT NULL COMMENT '职业',
    voice           VARCHAR(32)  NOT NULL COMMENT '音色',
    personality     VARCHAR(800) NOT NULL COMMENT '性格描述',
    quirks_text     VARCHAR(200) NULL     COMMENT '职业病描述',
    soul_traits     VARCHAR(64)  NOT NULL COMMENT '灵魂特质,逗号分隔',
    soul_quirk      VARCHAR(32)  NOT NULL COMMENT '小任性',
    relation_type   VARCHAR(32)  NOT NULL COMMENT '关系类型',
    pet_type        VARCHAR(16)  NOT NULL COMMENT '宠物类型: cat/dog',
    pet_name        VARCHAR(32)  NOT NULL COMMENT '宠物名',
    mood            VARCHAR(16)  NOT NULL COMMENT '今日心情',
    created_by      BIGINT       NOT NULL COMMENT '创建人ID',
    updated_by      BIGINT       NULL     COMMENT '修改人ID',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at      DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    UNIQUE KEY uk_device_id (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI伴侣配置表';
