-- PowerMem 初始化脚本
-- 用于 xiaozhi-esp32-server 记忆存储
-- 支持用户画像、记忆图谱和向量检索

-- 创建数据库
CREATE DATABASE IF NOT EXISTS powermem DEFAULT CHARACTER SET utf8mb4;
USE powermem;

-- 创建记忆表（支持向量存储）
CREATE TABLE IF NOT EXISTS memories (
    id BIGINT NOT NULL PRIMARY KEY,
    user_id VARCHAR(128) DEFAULT NULL COMMENT '用户ID',
    agent_id VARCHAR(128) DEFAULT NULL COMMENT '代理ID',
    run_id VARCHAR(128) DEFAULT NULL COMMENT '运行ID',
    actor_id VARCHAR(128) DEFAULT NULL COMMENT '角色ID',
    hash VARCHAR(32) DEFAULT NULL COMMENT '内容哈希',
    document LONGTEXT DEFAULT NULL COMMENT '记忆文档内容',
    embedding VECTOR(1536) DEFAULT NULL COMMENT '向量嵌入（1536维）',
    metadata JSON DEFAULT NULL COMMENT '元数据',
    category VARCHAR(64) DEFAULT NULL COMMENT '分类',
    fulltext_content LONGTEXT DEFAULT NULL COMMENT '全文检索内容',
    created_at VARCHAR(128) DEFAULT NULL COMMENT '创建时间',
    updated_at VARCHAR(128) DEFAULT NULL COMMENT '更新时间',
    VECTOR KEY vidx (embedding) WITH (LIB=VSAG,DISTANCE=L2,M=16,EF_CONSTRUCTION=200,TYPE=HNSW,EF_SEARCH=64) BLOCK_SIZE 16384,
    FULLTEXT KEY fulltext_index_for_col_text (fulltext_content) WITH PARSER ik PARSER_PROPERTIES=(ik_mode="smart") BLOCK_SIZE 16384
) ORGANIZATION INDEX DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMPRESSION='zstd_1.3.8' REPLICA_NUM=1 BLOCK_SIZE=16384 USE_BLOOM_FILTER=FALSE ENABLE_MACRO_BLOCK_BLOOM_FILTER=FALSE TABLET_SIZE=134217728 PCTFREE=0;

-- 创建用户画像表（UserMemory 模式）
CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT NOT NULL PRIMARY KEY,
    user_id VARCHAR(128) DEFAULT NULL COMMENT '用户ID',
    profile_content LONGTEXT DEFAULT NULL COMMENT '画像内容',
    topics JSON DEFAULT NULL COMMENT '主题标签',
    created_at VARCHAR(128) DEFAULT NULL COMMENT '创建时间',
    updated_at VARCHAR(128) DEFAULT NULL COMMENT '更新时间',
    KEY idx_user_id (user_id) BLOCK_SIZE 16384 LOCAL
) ORGANIZATION INDEX DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMPRESSION='zstd_1.3.8' REPLICA_NUM=1 BLOCK_SIZE=16384 USE_BLOOM_FILTER=FALSE ENABLE_MACRO_BLOCK_BLOOM_FILTER=FALSE TABLET_SIZE=134217728 PCTFREE=0;

-- 创建知识图谱实体表
CREATE TABLE IF NOT EXISTS graph_entities (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT '实体名称',
    entity_type VARCHAR(64) DEFAULT NULL COMMENT '实体类型（person/place/concept/event等）',
    embedding VECTOR(1536) DEFAULT NULL COMMENT '实体向量嵌入',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_name (name) BLOCK_SIZE 16384 LOCAL,
    VECTOR KEY vidx (embedding) WITH (LIB=VSAG,DISTANCE=L2,M=16,EF_CONSTRUCTION=200,TYPE=HNSW,EF_SEARCH=64) BLOCK_SIZE 16384
) ORGANIZATION INDEX DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMPRESSION='zstd_1.3.8' REPLICA_NUM=1 BLOCK_SIZE=16384 USE_BLOOM_FILTER=FALSE ENABLE_MACRO_BLOCK_BLOOM_FILTER=FALSE TABLET_SIZE=134217728 PCTFREE=0;

-- 创建知识图谱关系表
CREATE TABLE IF NOT EXISTS graph_relationships (
    id BIGINT NOT NULL PRIMARY KEY,
    source_entity_id BIGINT(20) NOT NULL COMMENT '源实体ID',
    relationship_type VARCHAR(128) NOT NULL COMMENT '关系类型',
    destination_entity_id BIGINT(20) NOT NULL COMMENT '目标实体ID',
    user_id VARCHAR(128) DEFAULT NULL COMMENT '用户ID',
    agent_id VARCHAR(128) DEFAULT NULL COMMENT '代理ID',
    run_id VARCHAR(128) DEFAULT NULL COMMENT '运行ID',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_r_covering (user_id, source_entity_id, destination_entity_id, relationship_type) BLOCK_SIZE 16384 LOCAL
) ORGANIZATION INDEX DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMPRESSION='zstd_1.3.8' REPLICA_NUM=1 BLOCK_SIZE=16384 USE_BLOOM_FILTER=FALSE ENABLE_MACRO_BLOCK_BLOOM_FILTER=FALSE TABLET_SIZE=134217728 PCTFREE=0;

SELECT 'PowerMem database initialization completed!' AS status;
